### ISSUE TITLE
Can't run at starup

### ISSUE THREAD

**Issue by geofausto** [OzymandiasTheGreat/xpander#1]
Hi.
I can't make it run at startup. If I start it using terminal returns a error.

$ xpander-indicator 
Error loading new keyboard description
Error loading new keyboard description
(xpander-indicator:23664): Gdk-CRITICAL **: gdk_window_thaw_toplevel_updates: assertion 'window->update_and_descendants_freeze_count > 0' failed

Using Linux Mint 18.1 64bits.
Thanks.

**Comment by OzymandiasTheGreat** [comment]
Hello! Thank you for your interest.
Unfortunately that's a Gtk+ error and the message is unhelpful as per usual. I'll try to reproduce it in a virtual machine when I have more time, but this is going to take a while.

**Comment by geofausto** [comment]
I restarted Linux Mint using recovery mode for another reason and noticed that xpander-indicator runned on startup. Hope it can help you find some clue.
Thanks for your reply.

**Comment by reider-roque** [comment]
I am experiencing similar issue. After drilling down into the code I pinned this line - https://github.com/OzymandiasTheGreat/xpander/blob/master/xpander-indicator#L25

Commenting out that line solves the issue but deprives me of the tray menu. Replacing it with `self.indicator.set_menu(Gtk.Menu())` gives the same error. The issue may be with Gtk itself.

**Comment by OzymandiasTheGreat** [comment]
I'm sorry, I've been rather busy. Anyway, finally got around to installing linuxmint and while I do get that gtk error, everything runs just fine. I installed linuxmint 18.3 tho, that might be why.
@reider-roque As for that line, it's beyond strange. This would mean that no app with an app indicator can run. It might be a bug in the python bindings (wouldn't be the first) but if so it's fixed in the current version.

**Comment by OzymandiasTheGreat** [comment]
There are no more gtk dependencies, so give it a try if you may.
