### ISSUE TITLE
Xpander AppImAGE not working

### ISSUE THREAD

**Issue by rita-shopify** [OzymandiasTheGreat/xpander#5]
Labas @OzymandiasTheGreat ,

First of all thank you for your hard work on your various projects!
I tried to use Xpander Appimage but it seems something is wrong.
Screenshot below:

![image](https://user-images.githubusercontent.com/50876635/77830195-8bbc5a80-712f-11ea-971c-6b646b254182.png)

For info I am using Linux Mint 19.3 X64.

Any help would be appreciated!
Ačiū

**Comment by OzymandiasTheGreat** [comment]
First thing, sorry, been out with particularly bad flu for over a month and I'm still not fully back.
Anyway, I'd need to see the full error. Try control-c when the error dialog is focused, should copy the full text.
This is probably a runpy bug I filed upstream, it's fixed by now, but it'll be some time before I make a new release with the fix.

**Comment by riadhtaihi** [comment]
Hi @OzymandiasTheGreat Hope you will feel better soon!
The system does unfortunately not let me copy and paste from that error.
Tried to look for the log file but hard to find the path.

I was using Textexpander with the company I am working with but when I decided to completely move from Mac to Linux, They said they don't have a Linux version.
I have tons of snippets there in CSV, does your app have an import possibility ? (They all have smileys btw), does your app support them?

I am ready to donate to you if it is fixed and it has the features mentioned above, as I do not plan to get back to Mac or Windows anymore, as I found all alternative stuff with Linux and at a much better speed and stability.

Let me know if you need further info..

Thx!
Riadh

**Comment by OzymandiasTheGreat** [comment]
Ok, you can mostly disregard my previous comment because apparently I was still feverish.
That control-c suggestion? That's a Windows thing, I got confused.

Anyway, after rereading the error message, it seems this is caused by a missing optional dependency on older versions of python. I can't be 100% sure without seeing the full error message, but we can check rather easily.
In the terminal enter this command `sudo pip3 install importlib-resources` and when it completes try starting xpander again. It should work now.

As for the import from textexpander functionality, I'd be very interested in adding this, but I'd need a sample textexpander csv for analysis and testing so if you can provide that I'll do it.

P.S. Re:smileys if you mean emoji, then yes, emoji is fully supported.

**Comment by riadhtaihi** [comment]
Thank you very much @OzymandiasTheGreat 
It was indeed the missing dependency that caused the issue 👍 
It starts normally now ;)

Just for information, I had my old sentences from TEXTEXPANDER and I tried to copy them to XPANDER, but only the text copies (Emojies don't unfortunately). Maybe there is a special format?

I can send you an example of TE that I use:

> Hello 🙋
> I'm Riadh from XXXX and it will be my pleasure to help you today!
> Glad to talk to talk to you by the way 🤝 

Attached is an export example from the current app that I am using on Windows.

Thank you in advance!

[My-Snippets Example.zip](https://github.com/OzymandiasTheGreat/xpander/files/4433242/My-Snippets.Example.zip)

**Comment by OzymandiasTheGreat** [comment]
Hmm, what do you mean emojis don't copy? Copy/pasting and typing emojis into xpander editor works on my end. What happens when you try to paste emoji into xpander editor? Note, since you're on Linux Mint emojis will probably display as black and white on your machine. They will look just fine on other devices.

Re:textexpander csv. First column seems like the shortcut, second column is the expanded text, ~what's the 3rd column?~ Once I know how to treat this, I can implement import :)

After some googling I can see that 3rd column is the label. I should have import working by the end of next weekend, *maybe* sooner.

**Comment by rita-shopify** [comment]
Thx @OzymandiasTheGreat No rush! 
For the Emojies,

When I type the abbreviation, the text shows normally on the field I need, however the Emojies do not show, while they show normally on the Xpander windows.

Does that make sense?

I am attaching a screen record, thx!
[Emojies not working properly.mp4.zip](https://github.com/OzymandiasTheGreat/xpander/files/4433534/Emojies.not.working.properly.mp4.zip)

**Comment by OzymandiasTheGreat** [comment]
There's your problem. You set phrase expansion method as `type`. That method, while the most reliable and fastest, only supports inserting characters defined in your current keyboard layout. That means only plain text and no emoji.
Set it to `paste` and it should work as intended (altho there might be a slight delay in expansion).

**Comment by rita-shopify** [comment]
All good now, I forgot that I've set it to type instead of paste.
Thank you very much!

**Comment by OzymandiasTheGreat** [comment]
So once again, I prove that developers can't estimate time.
Importing csv is done, you can download new version on releases page.
Then click new button and choose import csv, that's it.

If you wish to support my work, you can do so here: https://www.patreon.com/ozymandias
Also, if you read any tech or productivity blogs, please send them a tip about xpander. This project desperately needs more love!

If everything is working for you, please close this issue.

**Comment by riadhtaihi** [comment]
Thanks again Tomas!
The imported snippets do not seem to trigger strangely. But no big deal, You've already made a great job!

I would like to support with a one time donation. Send me your Revolut or Paypal please ;)
Will definitely talk about your project in the Internet, as your app can even replace the TEXT EXPANDER that is used for companies. I'm sure you can much better job than they did.
Let's stay in touch (You already have my Whatsapp).

I will close this issue, ✔️
